# @package _global_

defaults:
  - _self_
  - datamodule: mnist.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "predict"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
