# @package _global_

defaults:
  - _self_
  - datamodule: cifar.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: cifar.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "predict"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: logs/train/runs/2022-09-09_13-23-14/checkpoints/epoch_003.ckpt

# image: https://raw.githubusercontent.com/pytorch/hub/master/images/dog.jpg
image: tmp/dog.jpg